exclude: ^(buildspec.yml|.pre-commit-config.yaml)$
fail_fast: true
repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.17
  hooks:
  - id: isort
    # language_version: python3.6
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: trailing-whitespace
  - id: flake8
    additional_dependencies:
    - flake8-bugbear>=19.3.0
    - flake8-builtins>=1.4.1
    - flake8-commas>=2.0.0
    - flake8-comprehensions>=2.1.0
    - flake8-debugger>=3.1.0
    - flake8-pep3101>=1.2.1
    # language_version: python3.6
  - id: pretty-format-json
    args:
    - --autofix
    - --indent=4
    - --no-sort-keys
  - id: check-merge-conflict
  # - id: check-yaml  # doesn't work with CloudFormation templates/intrinsics, should use cfn-lint instead
    # language_version: python3.6
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.3.0
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-mock-methods
  - id: python-no-log-warn
- repo: https://github.com/PyCQA/bandit
  rev: f5a6f0ca62  # TODO: update once a release > 1.5.1 hits with this change in
  hooks:
  - id: bandit
    files: "^src/"
    # have to skip B101, contract tests use it and there's no way to skip for specific files
    # have to skip B322, as there is no way to indicate the codebase is Python 3 only (input only vulnerable in Py2)
    args: ["--skip", "B101,B322"]
- repo: local
  hooks:
  - id: git-secrets
    name: git-secrets
    description: Run git-secrets
    entry: git-secrets --scan
    language: system
    always_run: true
  - id: pylint-local
    name: pylint-local
    description: Run pylint in the local virtualenv
    entry: pylint "setup.py" "src/" "tests/"
    language: system
    # ignore all files, run on hard-coded modules instead
    pass_filenames: false
    always_run: true
  - id: pytest-local
    name: pytest-local
    description: Run pytest in the local virtualenv
    # although we mock SDK calls, credentials must be set, otherwise the credential-checking code
    # in boto_helpers.py fails. this probably needs fixing properly in future.
    # on the other hand, this means that accidentally exported creds aren't honoured when running
    # tests, also a good thing
    entry: >
      env AWS_ACCESS_KEY_ID=""
      AWS_SECRET_ACCESS_KEY=""
      AWS_SESSION_TOKEN=""
      AWS_DEFAULT_REGION="us-east-1"
      pytest
      --cov="rpdk.core"
      --doctest-modules
      --random-order-bucket="parent"
      "tests/"
      --pyargs "rpdk.core"
      --verbose
    language: system
    # ignore all files, run on hard-coded modules instead
    pass_filenames: false
    always_run: true
